name: paddle_pgnet
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - attr=2.5.2=h39aace5_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_3
  - libcap=2.77=h3ff7636_0
  - libdrm=2.4.125=hb03c661_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=258.2=h6569c3e_1
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - nvtop=3.2.0=h2d0b736_0
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=hd63d673_1_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tree=2.2.1=hb9d3cd8_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aistudio-sdk==0.3.8
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - bce-python-sdk==0.9.53
      - certifi==2025.10.5
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorlog==6.10.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - future==1.0.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.5
      - idna==3.11
      - imageio==2.37.2
      - imagesize==1.4.1
      - lazy-loader==0.4
      - lmdb==1.7.5
      - modelscope==1.32.0
      - networkx==3.5
      - numpy==2.2.6
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.9.6.50
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nvtx-cu11==11.8.86
      - opencv-contrib-python==4.10.0.84
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.3.0
      - packaging==25.0
      - paddleocr==3.3.2
      - paddlepaddle-gpu==3.2.0
      - paddlex==3.3.9
      - pandas==2.3.3
      - pillow==12.0.0
      - prettytable==3.17.0
      - protobuf==6.33.0
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyclipper==1.3.0.post6
      - pycryptodome==3.23.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pypdfium2==5.0.0
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rapidfuzz==3.14.3
      - requests==2.32.5
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.16.3
      - shapely==2.1.2
      - shellingham==1.5.4
      - simsimd==6.5.3
      - six==1.17.0
      - sniffio==1.3.1
      - stringzilla==4.2.3
      - tifffile==2025.10.16
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
prefix: /home/sungarala/.conda/envs/paddle_pgnet
